version: '3.7'
services:
  openproject-seeder:
    container_name: openproject-seeder
    image: openproject/community:11.1
    #user: "1001:0" # needs root access
    depends_on:
      - openproject-db
    environment:
      SECRET_KEY_BASE: jngsecret
      DATABASE_URL: "postgres://openproject:openproject@openproject-db:5432/openproject?encoding=utf8&pool=5&timeout=5000&reconnect=true"
      OPENPROJECT_RAILS_CACHE_STORE: file_store
      PASSENGER_START_TIMEOUT: 180
    volumes:
      - openproject-static:/var/openproject/assets
    networks:
      app_net:
    ports:
      - 80:8080
    command: "./docker/prod/entrypoint.sh ./docker/prod/seeder"
  openproject-db:
    container_name: openproject-db
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: openproject
      POSTGRES_USER: openproject
      POSTGRES_DB: openproject
    volumes:
      - openproject-pgdata:/var/lib/postgresql/data
    networks:
      app_net:
    ports:
      - 5432:5432
networks:
  app_net:
    name: app_net
    driver: bridge
volumes:
  openproject-pgdata:
    name: openproject-pgdata
  openproject-static:
    name: openproject-static
