apiVersion: v1
kind: Template
metadata:
  name: openproject
  annotations:
    description: "OpenProject - Online Open-Source Project Management"
    tags: "projectmanagement,openproject"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "jngrb"
    template.openshift.io/documentation-url: "https://github.com/jngrb/openproject-openshift/blob/master/README.md"
    template.openshift.io/support-url: "https://github.com/jngrb/openproject-openshift/issues"
parameters:
- name: EXTERNAL_OPENPROJECT_HOST
  description: Public application URL of OpenProject (Route/host)
  required: true
- name: INTERNAL_OPENPROJECT_HOST
  description: Private application URL of OpenProject (Route/host)
  required: true
- name: JENKINSFILE_REPO
  description: Jenkins source repository
  value: https://github.com/jngrb/openproject-openshift.git
- name: GIT_BRANCH
  description: branch in source repository
  value: openid_connect
- name: COMMUNITY_IMAGE_NAME
  description: Image name of the OpenProject Community Docker Image to be deployed
  value: openproject/community
- name: COMMUNITY_IMAGE_TAG
  description: Tag of the Openproject Docker Image to deploy
  value: "10.6"
- name: DOCKER_PATH
  description: Path to entrypoint inside docker image
  value: ./docker
- name: BUILD_FORK_IMAGE
  description: Care for a forked OpenProject repository
  value: "false"
- name: DATABASE_SECRET
  description: Name of the secret with the database reference DATABASE_URL
  value: openproject-database-secret
- name: PVC_SIZE
  description: PVC size for Apps, Config and Data
  value: 4Gi
- name: OIDC_METADATA_URL
  description: Configuration URL for the OpenID-Connect provider
  value: https://keycloak.apps.ingenieure.cloud/auth/realms/master/.well-known/openid-configuration
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
    name: update-pipeline
  name: update-pipeline
  spec:
    source:
      type: Git
      git:
        uri: "${JENKINSFILE_REPO}"
        ref: "${GIT_BRANCH}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
          - name: EXTERNAL_OPENPROJECT_HOST
            value: "${EXTERNAL_OPENPROJECT_HOST}"
          - name: INTERNAL_OPENPROJECT_HOST
            value: "${INTERNAL_OPENPROJECT_HOST}"
          - name: COMMUNITY_IMAGE_NAME
            value: "${COMMUNITY_IMAGE_NAME}"
          - name: COMMUNITY_IMAGE_TAG
            value: "${COMMUNITY_IMAGE_TAG}"
          - name: DOCKER_PATH
            value: "${DOCKER_PATH}"
          - name: BUILD_FORK_IMAGE
            value: "${BUILD_FORK_IMAGE}"
          - name: DATABASE_SECRET
            value: "${DATABASE_SECRET}"
          - name: PVC_SIZE
            value: "${PVC_SIZE}"
          - name: OIDC_METADATA_URL
            value: "${OIDC_METADATA_URL}"
