apiVersion: v1
kind: Template
metadata:
  name: openproject-upgrade
  annotations:
    description: "OpenProject - Online Open-Source Project Management"
    tags: "projectmanagement,openproject"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "jngrb"
    template.openshift.io/documentation-url: "https://github.com/jngrb/openproject-openshift/blob/master/README.md"
    template.openshift.io/support-url: "https://github.com/jngrb/openproject-openshift/issues"
parameters:
- name: COMMUNITY_IMAGE_TAG
  description: Tag of the OpenProject Community Docker Image to be deployed
  value: '10.4'
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: community-upgrade
      app: openproject
    name: community-upgrade
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: openproject/community:${COMMUNITY_IMAGE_TAG}
      generation: null
      importPolicy: {}
      name: '${COMMUNITY_IMAGE_TAG}'
      referencePolicy:
        type: Source
