apiVersion: v1
kind: Template
metadata:
  name: openproject-upgrade
  annotations:
    description: "OpenProject - Online Open-Source Project Management"
    tags: "projectmanagement,openproject"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "jngrb"
    template.openshift.io/documentation-url: "https://github.com/jngrb/openproject-openshift/blob/master/README.md"
    template.openshift.io/support-url: "https://github.com/jngrb/openproject-openshift/issues"
parameters:
- name: COMMUNITY_IMAGE_TAG
  description: Tag of the OpenProject Community Docker Image to be deployed
  value: '10.4'
- name: SECRET_KEY_BASE
  description: Secret key for the OpenProject instance
  value: dkp-spielwiese
- name: DATABASE_URL
  description: Database reference (usually postgresql)
  value: >-
    postgres://openproject:openproject@postgresql.openproject.svc:5432/openproject
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: community-upgrade
      app: community-upgrade
    name: community-upgrade
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: openproject/community:${COMMUNITY_IMAGE_TAG}
      generation: null
      importPolicy: {}
      name: '${COMMUNITY_IMAGE_TAG}'
      referencePolicy:
        type: Source
- apiVersion: batch/v1
  kind: Job
  metadata:
    generateName: "community-upgrade-${COMMUNITY_IMAGE_TAG}-"
  spec:
    concurrencyPolicy: Replace
    activeDeadlineSeconds: 3600
    template:
      metadata:
       generateName: "community-upgrade-${COMMUNITY_IMAGE_TAG}-"
      spec:
        nodeSelector:
          appclass: main
        containers:
        - name: community-upgrade
          image: openproject/community:${COMMUNITY_IMAGE_TAG}
          imagePullPolicy: Always
          command:
            - ./docker/entrypoint.sh
          args:
            - ./docker/seeder
          env:
            - name: SECRET_KEY_BASE
              value: ${SECRET_KEY_BASE}
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: RAILS_CACHE_STORE
              value: file_store
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/openproject/assets
              name: openproject-data
              subPath: assets
            - mountPath: /var/openproject/pgdata
              name: community-upgrade-1
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: openproject-data
          persistentVolumeClaim:
            claimName: openproject-data
        - emptyDir: {}
          name: community-upgrade-1
